// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "My fizzbuzz api": spec TestHelpers
//
// Command:
// $ goagen
// --design=github.com/mrsinham/fb/http/design
// --out=$(GOPATH)/src/github.com/mrsinham/fb/http/goa
// --version=v1.3.0

package test
